# Generated by Django 3.2 on 2024-11-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('usuario_rol', models.CharField(max_length=50, verbose_name='Especifique el rol: ')),
                ('usuario_nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_fecha', models.DateField(verbose_name='Fecha')),
                ('ticket_prioridad', models.CharField(max_length=20, verbose_name='Prioridad (Alta-Media-Baja): ')),
                ('ticket_descripcion', models.CharField(max_length=100, verbose_name='Descripción: ')),
                ('ticket_numero_cliente', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario', verbose_name='Nombre usuario')),
            ],
        ),
    ]
