# Generated by Django 3.2 on 2024-11-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ticket_ticket_numero_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_numero_cliente',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario', verbose_name='Nombre usuario'),
        ),
    ]
