# Generated by Django 3.2 on 2024-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_ticket_ticket_numero_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_nombre_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_rol',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Especifique el rol: '),
        ),
    ]
