# Generated by Django 3.2 on 2024-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20241121_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_nombre_usuario',
            field=models.CharField(default=1234, max_length=50, verbose_name='Nombre usuario'),
            preserve_default=False,
        ),
    ]
