# Generated by Django 3.2 on 2024-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuario_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_numero_cliente',
            field=models.CharField(max_length=50, verbose_name='Nombre usuario'),
        ),
        '''migrations.RemoveField(
            model_name='usuario',
            name='usuario_nombre_usuario',
        ),'''
    ]
